/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/apps/': RouteRecordInfo<
      '/apps/',
      '/apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps/[id]': RouteRecordInfo<
      '/apps/[id]',
      '/apps/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/apps/create': RouteRecordInfo<
      '/apps/create',
      '/apps/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/Login/': RouteRecordInfo<
      '/auth/Login/',
      '/auth/Login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/Register/': RouteRecordInfo<
      '/auth/Register/',
      '/auth/Register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/canvas': RouteRecordInfo<
      '/canvas',
      '/canvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/channels/': RouteRecordInfo<
      '/channels/',
      '/channels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/channels/[id]': RouteRecordInfo<
      '/channels/[id]',
      '/channels/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/channels/create': RouteRecordInfo<
      '/channels/create',
      '/channels/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devices/': RouteRecordInfo<
      '/devices/',
      '/devices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devices/[id]': RouteRecordInfo<
      '/devices/[id]',
      '/devices/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/onboarding/': RouteRecordInfo<
      '/onboarding/',
      '/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/statistics/': RouteRecordInfo<
      '/statistics/',
      '/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/update-logs/': RouteRecordInfo<
      '/update-logs/',
      '/update-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/updates-bundles/': RouteRecordInfo<
      '/updates-bundles/',
      '/updates-bundles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/updates-bundles/[id]': RouteRecordInfo<
      '/updates-bundles/[id]',
      '/updates-bundles/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/updates-bundles/upload/': RouteRecordInfo<
      '/updates-bundles/upload/',
      '/updates-bundles/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/apps/index.vue': {
      routes:
        | '/apps/'
      views:
        | never
    }
    'src/pages/apps/[id].vue': {
      routes:
        | '/apps/[id]'
      views:
        | never
    }
    'src/pages/apps/create.vue': {
      routes:
        | '/apps/create'
      views:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/Login/index.vue': {
      routes:
        | '/auth/Login/'
      views:
        | never
    }
    'src/pages/auth/Register/index.vue': {
      routes:
        | '/auth/Register/'
      views:
        | never
    }
    'src/pages/canvas.vue': {
      routes:
        | '/canvas'
      views:
        | never
    }
    'src/pages/channels/index.vue': {
      routes:
        | '/channels/'
      views:
        | never
    }
    'src/pages/channels/[id].vue': {
      routes:
        | '/channels/[id]'
      views:
        | never
    }
    'src/pages/channels/create.vue': {
      routes:
        | '/channels/create'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/devices/index.vue': {
      routes:
        | '/devices/'
      views:
        | never
    }
    'src/pages/devices/[id].vue': {
      routes:
        | '/devices/[id]'
      views:
        | never
    }
    'src/pages/onboarding/index.vue': {
      routes:
        | '/onboarding/'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/statistics/index.vue': {
      routes:
        | '/statistics/'
      views:
        | never
    }
    'src/pages/update-logs/index.vue': {
      routes:
        | '/update-logs/'
      views:
        | never
    }
    'src/pages/updates-bundles/index.vue': {
      routes:
        | '/updates-bundles/'
      views:
        | never
    }
    'src/pages/updates-bundles/[id].vue': {
      routes:
        | '/updates-bundles/[id]'
      views:
        | never
    }
    'src/pages/updates-bundles/upload/index.vue': {
      routes:
        | '/updates-bundles/upload/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
